create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255)  NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
  );

create TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORIES_NAME UNIQUE (name)
  );

create TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(1255) NOT NULL,
  category  BIGINT  NOT NULL,
  confirmed_requests BIGINT,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  description VARCHAR(1255) NOT NULL,
  event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  initiator BIGINT  NOT NULL,
  lat REAL NOT NULL,
  lon REAL NOT NULL,
  paid Boolean,
  participant_limit BIGINT,
  published_on  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  request_moderation Boolean,
  state_action VARCHAR(20),
  title VARCHAR(200),
  CONSTRAINT fk_events_to_users FOREIGN KEY(initiator) REFERENCES users(id),
  CONSTRAINT fk_events_to_categories FOREIGN KEY(category) REFERENCES categories(id)
  );