version: '3.9'
services:
  stats-server:
    build:
      statistics/stats-server
    container_name: stats-server2
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      #      TZ: Europe/Moscow
      URL_DB: stats-db:5432/stats-db2
      USERNAME_DB: test
      PASSWORD_DB: test

  stats-db:
    image: postgres:14-alpine
    #    build:
    #      context: ./statistics/stats-server/
    #      dockerfile: ./statistics/stats-server/Dockerfile.postgres
    #    volumes:
    #        - /var/lib/postgresql/data/
    volumes:
      - ./statistics/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - /var/lib/postgresql/data/
    container_name: explore-stats-db
    ports:
      - "6541:5432"
    environment:
      #      TZ: Europe/Moscow
      POSTGRES_DB: stats-db2
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  #  ewm-service:
  #    ports:
  #      - "8080:8080"
  #
  #  ewm-db:
  #    image: postgres:14-alpine
  ewm-service:
    build:
      main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    #      - stats-server
    environment:
      #      TZ: Europe/Moscow
      URL_DB_MAIN: ewm-db:5432/explore-with-me-main
      USERNAME_DB_MAIN: test
      PASSWORD_DB_MAIN: test
      STATS_URL: http://stats-server2:9090
  #      STATS_SERVER_URL: http://stats-server:9090
  ewm-db:
    image: postgres:14-alpine
    build:
      context: ./main-service/
      dockerfile: ./Dockerfile.postgres
    volumes:
      - /var/lib/postgresql/data/

    container_name: explore-main-db
    ports:
      - "6543:5432"
    environment:
      #      TZ: Europe/Moscow
      POSTGRES_DB: explore-with-me-main
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test